name: Build Package

on:
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            repository: google/bbr
            ref: v3
            path: bbr

        - name: Get current time
          id: time
          run: echo "time=$(date -u "+%Y-%m-%d-%H%M%S")" >> $GITHUB_OUTPUT

        - name: Setup dependencies
          run: |
            sudo apt-get update
            sudo apt-fast install -y build-essential \
              bc kmod cpio flex libncurses5-dev \
              libelf-dev libssl-dev dwarves bison debhelper \
              gawk openssl libssl-dev dkms libudev-dev \
              libpci-dev libiberty-dev autoconf llvm \
              gcc-13 g++-13
        

        - name: Setup ccache
          uses: hendrikmuhs/ccache-action@v1.2
          with:
            max-size: 1000M

        - name: Build
          working-directory: bbr
          run: |
            # Setup ccache
            export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
            # Download .config
            curl -sSL https://raw.githubusercontent.com/Zxilly/bbr-v3-deb/master/.config > .config
            # Setup
            make olddefconfig
            make prepare
            # Build
            nice make -j`nproc` deb-pkg V=1
            
        - name: Release
          uses: ncipollo/release-action@v1
          with:
            artifacts: "linux-*"
            prerelease: true
            tag: ${{ steps.time.outputs.time }}
        